name: Vulnerability Scanning

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Build
    runs-on: "ubuntu-22.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner for FileSystem
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Run Trivy vulnerability scanner for Container App
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'photoprism/photoprism:latest'
          format: 'sarif'
          output: 'trivy-results-container.sarif'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEIDUM'

      - name: Run Trivy vulnerability scanner for Container DB MariaDB
        uses: aquasecurity/trivy-action@master
        with:
            image-ref: 'mariadb:10.7'
            format: 'sarif'
            output: 'trivy-results-container.sarif'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH,MEIDUM'

      - name: Upload Trivy scan results to GitHub Security tab for FileSystem
        uses: github/codeql-action/upload-sarif@v2
        with:
          category: "filesystem"
          sarif_file: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab for Container App
        uses: github/codeql-action/upload-sarif@v2
        with:
            category: "container-app"
            sarif_file: 'trivy-results-container.sarif'

      - name: Upload Trivy scan results to GitHub Security tab for Container DB
        uses: github/codeql-action/upload-sarif@v2
        with:
            category: "container-db"
            sarif_file: 'trivy-results-container.sarif'